config/routes.rb
Rails.application.routes.draw do
  post "location", to: "locations#update", as: :update_location
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "homepage#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def update
    postCode = params[:location][:postCode]
    cache_key = "weather_data_#{postCode}"
    cached_data = Rails.cache.read(cache_key)
    @weather = cached_data if cached_data

    Rails.cache.fetch(cache_key, expires_in: 30.minutes) do
      @weather = retrieve_weather_data_for_zipcode(lat: params[:location][:latitude], lon: params[:location][:longitude], country_code: params[:location][:countryCode])
    end

    @weather_attributes = {
      cached: cached_data.present?,
      temperature: @weather.temperature,
      current_condition: @weather.current_condition,
      precipitation: @weather.precipitation,
      humidity: @weather.humidity,
      wind_speed: @weather.wind_speed,
      extended_forecast: @weather.extended_forecast
    }

    respond_to do |format|
      format.turbo_stream
    end
  end

  def retrieve_weather_data_for_zipcode(lat:, lon:, country_code:)
    WeatherApi.new(lat:, lon:, country_code:)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/homepage/index.html.erb
<h1>Weather</h1>
<%= form_tag(update_location_path, method: "post", id: "geocode-form", data: { turbo_stream: true }) do %>
  <%= text_field_tag :address, nil, placeholder: "Enter Address", id: "address-input" %>
  <%= submit_tag "Get the Weather" %>
<% end %>

<turbo-frame id="location"></turbo-frame>

<div id="map-container"></div>

<script type="text/javascript">
  const jwt = "<%= MapJwt.new.jwt %>";
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- TODO: Add the value of data-initial-token with a JWT
    dynamically generated on the server -->
    <script src="https://cdn.apple-mapkit.com/mk/5.x.x/mapkit.core.js"
        crossorigin async
        data-callback="initMapKit"
        data-libraries="map,annotations,services"
        data-initial-token="">
    </script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/_weather.html.erb
<section class="current">
  <%= image_tag(weather[:current_condition], size: "50x50") %>
  <b class="big-temperature"><%= weather[:temperature] %></b>
  <div>
    Precipitation: <%= weather[:precipitation] %><br />
    Humidity: <%= weather[:humidity] %><br />
    Wind: <%= weather[:wind_speed] %>
  </div>
  <% if weather[:cached] %>
    <div class="cache">
      Data was retrieved from cache.
    </div>
  <% end %>
</section>

<div class="extended-forecast">
  <% weather[:extended_forecast].each do |day| %>
    <section>
      <span><%= day[:date] %></span>
      <span>
        <%= image_tag(day[:conditionCode], size: "30x30") %>
      </span>
      <span>
        <%= day[:temperatureMax] %>°
        <%= day[:temperatureMin] %>°
      </span>
    </section>
  <% end %>
</div>

app/views/locations/update.turbo_stream.erb
<%= turbo_stream.update 'location', partial: 'weather', locals: { weather: @weather_attributes } %>